insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (1, 'Alyda Hollyard', '559 Granby Point', '', 8, '9/18/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (2, 'Wilona Crosby', '18 Doe Crossing Avenue', '', 7, '1/3/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (3, 'Mel Whitehall', '89546 Springview Place', '', 6, '2/9/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (4, 'Kathe Tinker', '304 Summer Ridge Parkway', '', 5, '1/7/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (5, 'Bail Robert', '62 Lyons Drive', '', 4, '10/11/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (6, 'Deana Foskett', '6 Basil Junction', '', 4, '12/11/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (7, 'Rae Speight', '449 Del Mar Alley', '', 6, '9/25/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (8, 'Brenn Eivers', '8 Alpine Crossing', '', 2, '2/9/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (9, 'Donetta Yokley', '197 Red Cloud Alley', '', 1, '4/5/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (10, 'Elna Kellart', '992 Dryden Parkway', '', 3, '4/21/2020', '');
