insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (56, 'Alyda Hollyard', '559 Granby Point', '', 36, '9/18/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (57, 'Wilona Crosby', '18 Doe Crossing Avenue', '', 92, '1/3/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (92, 'Mel Whitehall', '89546 Springview Place', '', 40, '2/9/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (82, 'Kathe Tinker', '304 Summer Ridge Parkway', '', 47, '1/7/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (39, 'Bail Robert', '62 Lyons Drive', '', 40, '10/11/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (45, 'Deana Foskett', '6 Basil Junction', '', 30, '12/11/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (8, 'Rae Speight', '449 Del Mar Alley', '', 46, '9/25/2019', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (42, 'Brenn Eivers', '8 Alpine Crossing', '', 59, '2/9/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (90, 'Donetta Yokley', '197 Red Cloud Alley', '', 22, '4/5/2020', '');
insert into cliente (idCliente, nome, endereco, bairro, idCidade, dataCadastro, cancelado) values (3, 'Elna Kellart', '992 Dryden Parkway', '', 65, '4/21/2020', '');
