insert into tarifa (idTarifa, descricao, valor) values (1, 'cliente com desconto (10%)', 194);
insert into tarifa (idTarifa, descricao, valor) values (2, 'cliente comum', 332);
insert into tarifa (idTarifa, descricao, valor) values (3, 'cliente com desconto (25%)', 167);
insert into tarifa (idTarifa, descricao, valor) values (4, 'cliente comum', 260);
insert into tarifa (idTarifa, descricao, valor) values (5, 'cliente comum', 336);
insert into tarifa (idTarifa, descricao, valor) values (6, 'cliente comum', 349);
insert into tarifa (idTarifa, descricao, valor) values (7, 'cliente comum', 286);
insert into tarifa (idTarifa, descricao, valor) values (8, 'cliente com desconto (20%)', 236);
insert into tarifa (idTarifa, descricao, valor) values (9, 'cliente comum', 266);
insert into tarifa (idTarifa, descricao, valor) values (10, 'cliente com desconto (30%)', 176);
